Calling Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from datacleaner import autoclean

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor

from sklearn.metrics import mean_squared_error, r2_score

import warnings
warnings.filterwarnings('ignore')

Uploading Data

In [2]:
df = pd.read_csv(r"C:\Users\Saidabrorkhon\Downloads\cancer_reg.csv")

Data Exploration

In [4]:
df.head()

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,medianage,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
0,1397.0,469,164.9,489.8,61898,260131,11.2,499.748204,"(61494.5, 125635]",39.3,...,NaN,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
1,173.0,70,161.3,411.6,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",33.0,...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
2,102.0,50,174.7,349.7,49348,21026,14.6,47.560164,"(48021.6, 51046.4]",45.0,...,43.5,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
3,427.0,202,194.8,430.4,44243,75882,17.1,342.637253,"(42724.4, 45201]",42.8,...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.0,26,144.4,350.1,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",48.3,...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avganncount              3047 non-null   float64
 1   avgdeathsperyear         3047 non-null   int64
 2   target_deathrate         3047 non-null   float64
 3   incidencerate            3047 non-null   float64
 4   medincome                3047 non-null   int64
 5   popest2015               3047 non-null   int64
 6   povertypercent           3047 non-null   float64
 7   studypercap              3047 non-null   float64
 8   binnedinc                3047 non-null   object
 9   medianage                3047 non-null   float64
 10  medianagemale            3047 non-null   float64
 11  medianagefemale          3047 non-null   float64
 12  geography                3047 non-null   object
 13  percentmarried           3047 non-null   float64
 14  pctnohs18_24             3047 non-null   float64
 15  pcths18_24               3047 non-null   float64
 16  pctsomecol18_24          762 non-null    float64
 17  pctbachdeg18_24          3047 non-null   float64
 18  pcths25_over             3047 non-null   float64
 19  pctbachdeg25_over        3047 non-null   float64
 20  pctemployed16_over       2895 non-null   float64
 21  pctunemployed16_over     3047 non-null   float64
 22  pctprivatecoverage       3047 non-null   float64
 23  pctprivatecoveragealone  2438 non-null   float64
 24  pctempprivcoverage       3047 non-null   float64
 25  pctpubliccoverage        3047 non-null   float64
 26  pctpubliccoveragealone   3047 non-null   float64
 27  pctwhite                 3047 non-null   float64
 28  pctblack                 3047 non-null   float64
 29  pctasian                 3047 non-null   float64
 30  pctotherrace             3047 non-null   float64
 31  pctmarriedhouseholds     3047 non-null   float64
 32  birthrate                3047 non-null   float64
dtypes: float64(28), int64(3), object(2)
memory usage: 785.7+ KB

Missing value function

In [13]:
class DataInfo:
  def __init__(self,df):
    self.df = df
    
  def missing_val(self):
   return self.df.isnull().sum()
  
  def duplicated_val(self):
    return self.df.duplicated().sum()

In [16]:
data_info = DataInfo(df)
data_info.missing_val()

avganncount                   0
avgdeathsperyear              0
target_deathrate              0
incidencerate                 0
medincome                     0
popest2015                    0
povertypercent                0
studypercap                   0
binnedinc                     0
medianage                     0
medianagemale                 0
medianagefemale               0
geography                     0
percentmarried                0
pctnohs18_24                  0
pcths18_24                    0
pctsomecol18_24            2285
pctbachdeg18_24               0
pcths25_over                  0
pctbachdeg25_over             0
pctemployed16_over          152
pctunemployed16_over          0
pctprivatecoverage            0
pctprivatecoveragealone     609
pctempprivcoverage            0
pctpubliccoverage             0
pctpubliccoveragealone        0
pctwhite                      0
pctblack                      0
pctasian                      0
pctotherrace                  0
pctmarriedhouseholds          0
birthrate                     0
dtype: int64

In [17]:
data_info.duplicated_val()

np.int64(0)

In [4]:
def fill_missing(df):
  for col in df.columns:
    if df[col].dtype == 'object':
      df[col].fillna(df[col].mode()[0], inplace=True)
    else:
      df[col].fillna(df[col].mean(), inplace=True)

fill_missing(df)

In [25]:
print(df['binnedinc'].nunique())
print(df['binnedinc'].unique())

10
[ 1.21838299  0.17341781 -0.52322564  0.52173953 -1.2198691  -0.87154737
  0.87006126 -1.56819082  1.56670471 -0.17490392]

In [21]:
data_info.missing_val()

avganncount                0
avgdeathsperyear           0
target_deathrate           0
incidencerate              0
medincome                  0
popest2015                 0
povertypercent             0
studypercap                0
binnedinc                  0
medianage                  0
medianagemale              0
medianagefemale            0
geography                  0
percentmarried             0
pctnohs18_24               0
pcths18_24                 0
pctsomecol18_24            0
pctbachdeg18_24            0
pcths25_over               0
pctbachdeg25_over          0
pctemployed16_over         0
pctunemployed16_over       0
pctprivatecoverage         0
pctprivatecoveragealone    0
pctempprivcoverage         0
pctpubliccoverage          0
pctpubliccoveragealone     0
pctwhite                   0
pctblack                   0
pctasian                   0
pctotherrace               0
pctmarriedhouseholds       0
birthrate                  0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avganncount              3047 non-null   float64
 1   avgdeathsperyear         3047 non-null   int64
 2   target_deathrate         3047 non-null   float64
 3   incidencerate            3047 non-null   float64
 4   medincome                3047 non-null   int64
 5   popest2015               3047 non-null   int64
 6   povertypercent           3047 non-null   float64
 7   studypercap              3047 non-null   float64
 8   binnedinc                3047 non-null   object
 9   medianage                3047 non-null   float64
 10  medianagemale            3047 non-null   float64
 11  medianagefemale          3047 non-null   float64
 12  geography                3047 non-null   object
 13  percentmarried           3047 non-null   float64
 14  pctnohs18_24             3047 non-null   float64
 15  pcths18_24               3047 non-null   float64
 16  pctsomecol18_24          3047 non-null   float64
 17  pctbachdeg18_24          3047 non-null   float64
 18  pcths25_over             3047 non-null   float64
 19  pctbachdeg25_over        3047 non-null   float64
 20  pctemployed16_over       3047 non-null   float64
 21  pctunemployed16_over     3047 non-null   float64
 22  pctprivatecoverage       3047 non-null   float64
 23  pctprivatecoveragealone  3047 non-null   float64
 24  pctempprivcoverage       3047 non-null   float64
 25  pctpubliccoverage        3047 non-null   float64
 26  pctpubliccoveragealone   3047 non-null   float64
 27  pctwhite                 3047 non-null   float64
 28  pctblack                 3047 non-null   float64
 29  pctasian                 3047 non-null   float64
 30  pctotherrace             3047 non-null   float64
 31  pctmarriedhouseholds     3047 non-null   float64
 32  birthrate                3047 non-null   float64
dtypes: float64(28), int64(3), object(2)
memory usage: 785.7+ KB

Encoding

In [3]:
class Cardinality:
    def __init__(self, df):
        self.df = df
        self.cat_cols = self.df.select_dtypes(include=['object'])

    def low_cardinality(self):
        return [col for col in self.cat_cols if self.df[col].nunique() <= 5]

    def medium_cardinality(self):
        return [col for col in self.cat_cols if 6 <= self.df[col].nunique() <= 50]

    def high_cardinality(self):
        return [col for col in self.cat_cols if self.df[col].nunique() > 50]

In [6]:
card = Cardinality(df)
print(card.low_cardinality())
print(card.medium_cardinality())
print(card.high_cardinality())

[]
['binnedinc']
['geography']

In [13]:
def encode(df):
  df_encoded = df.copy()
  low_cols = card.low_cardinality()
  if low_cols:
    df_encoded = pd.get_dummies(df_encoded, columns=low_cols, drop_first=True)

  medium_cols = card.medium_cardinality()
  for col in medium_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])

  high_cols = card.high_cardinality()
  for col in high_cols:
    freq = df_encoded[col].value_counts(normalize=True)
    df_encoded[col] = df_encoded[col].map(freq)

  return df_encoded
encode(df)

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,medianage,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
0,1397.000000,469,164.9,489.800000,61898,260131,11.2,499.748204,8,39.3,...,48.453774,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
1,173.000000,70,161.3,411.600000,48127,43269,18.6,23.111234,5,33.0,...,53.800000,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
2,102.000000,50,174.7,349.700000,49348,21026,14.6,47.560164,5,45.0,...,43.500000,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
3,427.000000,202,194.8,430.400000,44243,75882,17.1,342.637253,3,42.8,...,40.300000,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.000000,26,144.4,350.100000,49955,10321,12.5,0.000000,5,48.3,...,43.900000,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3042,1962.667684,15,149.6,453.549422,46961,6343,12.4,0.000000,4,44.2,...,54.900000,44.6,31.7,13.2,90.280811,3.837754,0.327613,1.700468,51.063830,7.773512
3043,1962.667684,43,150.1,453.549422,48609,37118,18.8,377.175494,5,30.4,...,53.300000,48.6,28.8,17.7,75.706245,2.326771,4.044920,14.130288,52.007937,8.186470
3044,1962.667684,46,153.9,453.549422,51144,34536,15.0,1968.959926,6,30.9,...,52.600000,47.8,26.6,16.8,87.961629,2.313188,1.316472,5.680705,55.153949,7.809192
3045,1962.667684,52,175.0,453.549422,50745,25609,13.3,0.000000,5,39.0,...,56.300000,49.6,29.5,14.0,92.905681,1.176562,0.244632,2.131790,58.484232,7.582938
3046,1962.667684,48,213.6,453.549422,41193,37030,13.9,0.000000,2,26.2,...,60.300000,22.9,25.1,12.6,70.098132,16.590100,3.177753,1.356457,56.040242,8.981723

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avganncount              3047 non-null   float64
 1   avgdeathsperyear         3047 non-null   int64
 2   target_deathrate         3047 non-null   float64
 3   incidencerate            3047 non-null   float64
 4   medincome                3047 non-null   int64
 5   popest2015               3047 non-null   int64
 6   povertypercent           3047 non-null   float64
 7   studypercap              3047 non-null   float64
 8   binnedinc                3047 non-null   int64
 9   medianage                3047 non-null   float64
 10  medianagemale            3047 non-null   float64
 11  medianagefemale          3047 non-null   float64
 12  geography                3047 non-null   int64
 13  percentmarried           3047 non-null   float64
 14  pctnohs18_24             3047 non-null   float64
 15  pcths18_24               3047 non-null   float64
 16  pctsomecol18_24          3047 non-null   float64
 17  pctbachdeg18_24          3047 non-null   float64
 18  pcths25_over             3047 non-null   float64
 19  pctbachdeg25_over        3047 non-null   float64
 20  pctemployed16_over       3047 non-null   float64
 21  pctunemployed16_over     3047 non-null   float64
 22  pctprivatecoverage       3047 non-null   float64
 23  pctprivatecoveragealone  3047 non-null   float64
 24  pctempprivcoverage       3047 non-null   float64
 25  pctpubliccoverage        3047 non-null   float64
 26  pctpubliccoveragealone   3047 non-null   float64
 27  pctwhite                 3047 non-null   float64
 28  pctblack                 3047 non-null   float64
 29  pctasian                 3047 non-null   float64
 30  pctotherrace             3047 non-null   float64
 31  pctmarriedhouseholds     3047 non-null   float64
 32  birthrate                3047 non-null   float64
dtypes: float64(28), int64(5)
memory usage: 785.7 KB

Scaling

In [15]:
def scaler(df):
  scaler =  StandardScaler()
  num_col = df.select_dtypes(include='number').columns
  df[num_col] = scaler.fit_transform(df[num_col])
scaler(df)
df.head()

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,medianage,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
0,0.558328,0.561518,-0.496057,0.761321,1.232312,0.478696,-0.886102,0.650277,1.218383,-0.131848,...,0.000000,0.042734,-0.427608,-0.857336,-0.113862,-0.448196,1.367088,-0.039818,0.245324,0.241011
1,-0.306003,-0.230067,-0.625801,-0.672179,0.088363,-0.180448,0.268698,-0.249816,0.173418,-0.270930,...,0.592879,0.254461,-0.657187,-0.644641,0.340912,-0.560060,0.380201,0.499790,-0.893428,-0.658382
2,-0.356140,-0.269746,-0.142865,-1.806881,0.189790,-0.248055,-0.355519,-0.203646,0.173418,-0.006012,...,-0.549357,-0.666550,0.745793,0.304306,0.444328,-0.575848,-0.301959,0.217176,0.487085,-0.962391
3,-0.126640,0.031811,0.581539,-0.327553,-0.234279,-0.081322,0.034617,0.353585,-0.523226,-0.054580,...,-0.904226,-0.655964,1.153933,0.942391,0.494549,-0.572892,-0.035483,-0.176530,-0.033835,-0.522020
4,-0.387917,-0.317360,-1.234876,-1.799549,0.240214,-0.280592,-0.683232,-0.293460,0.173418,0.066840,...,-0.504998,-0.645377,0.988126,0.566084,0.638610,-0.608154,-0.225352,-0.424035,0.423570,0.582401

Model Training

In [16]:
x = df.drop(columns=['target_deathrate'])
y = df['target_deathrate']

x_train, x_temp, y_train, y_temp = train_test_split(x, y, test_size=0.2, random_state=42)
x_test, x_val, y_test, y_val = train_test_split(x_temp, y_temp, test_size=0.5, random_state=42)

In [17]:
models = {
  'LinearRegression': LinearRegression(),
  'RandomForestRegressor': RandomForestRegressor(n_estimators=100, max_depth=10, min_samples_split=5, random_state=42),
  'DecisionTreeRegressor': DecisionTreeRegressor(max_depth=5, min_samples_split=5, random_state=42),
  'LGBMRegressor': LGBMRegressor(n_estimators=100, max_depth=10, random_state=42)
}

results = []
for name, model in models.items():
  model.fit(x_train, y_train)
  y_pred = model.predict(x_val)

  mse = mean_squared_error(y_val, y_pred)
  r2 = r2_score(y_val, y_pred)

  results.append({'Model': name, 'mse': mse, 'r2': r2})
result_df = pd.DataFrame(results).sort_values(by='r2', ascending=False)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000785 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 7593
[LightGBM] [Info] Number of data points in the train set: 2437, number of used features: 32
[LightGBM] [Info] Start training from score -0.002001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [18]:
result_df

                   Model       mse        r2
3          LGBMRegressor  0.333177  0.693143
1  RandomForestRegressor  0.474528  0.562957
0       LinearRegression  0.519243  0.521775
2  DecisionTreeRegressor  0.679904  0.373806